import { Trip } from "./trip";
export const Trips: Trip[] = [
    { name: "Peek into the Past", destination: "The Czech Republic", startDate: new Date("2023-06-25"), endDate: new Date("2023-06-28"), unitPrice: 459.99, freeSeats: 7, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Prague.jpg" },
    { name: "Phoenix from the Ashes", destination: "Poland", startDate: new Date("2023-05-10"), endDate: new Date("2023-05-17"), unitPrice: 609.99, freeSeats: 20, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Warsaw.jpg" },
    { name: "Law and Order", destination: "Germany", startDate: new Date("2023-08-11"), endDate: new Date("2023-08-14"), unitPrice: 929.99, freeSeats: 0, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Berlin.jpg" },
    { name: "What a Lovely Night", destination: "France", startDate: new Date("2023-09-20"), endDate: new Date("2023-09-22"), unitPrice: 419.99, freeSeats: 3, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Paris.jpg" },
    { name: "Tale of Two Cities", destination: "Hungary", startDate: new Date("2023-10-30"), endDate: new Date("2023-11-01"), unitPrice: 749.99, freeSeats: 8, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Budapest.jpg" },
    { name: "City of World's Desire", destination: "Türkiye", startDate: new Date("2023-07-01"), endDate: new Date("2023-07-15"), unitPrice: 1399.99, freeSeats: 5, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Istanbul.jpg" },
    { name: "Respublica Nostra", destination: "Italy", startDate: new Date("2023-03-10"), endDate: new Date("2023-03-21"), unitPrice: 1469.99, freeSeats: 14, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Naples.jpg" },
    { name: "Voices of the Past", destination: "Iraq", startDate: new Date("2023-10-16"), endDate: new Date("2023-10-21"), unitPrice: 839.99, freeSeats: 13, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Damascus.jpg" },
    { name: "Technopolis", destination: "Japan", startDate: new Date("2025-05-05"), endDate: new Date("2023-05-10"), unitPrice: 1869.99, freeSeats: 21, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Tokyo.jpg" },
    { name: "Colors All Around", destination: "Italy", startDate: new Date("2023-08-01"), endDate: new Date("2023-08-08"), unitPrice: 569.99, freeSeats: 7, description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nihil perferendis laudantium autem? Odio labore dolore debitis facere in recusandae nulla suscipit alias molestiae fugiat nesciunt itaque eos non deleniti, quos cum veniam facilis officiis nemo corporis. Deleniti minima excepturi culpa vero praesentium maiores, unde fuga totam accusantium dolores voluptatum!", imgPath: "../assets/img/tripImgs/Cinque_Terre.jpg" },
]